const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const lib=()=>import('../scripts/footystats.mjs');
test('FootyStats normalizer preserves zero, missing values and negative sentinels',async()=>{const l=await lib();const p=l.normalizePlayer({id:7,goals_overall:0,assists_overall:'',detailed:{xg_total_overall:-1,shots_per_90_overall:'1.25',duels_won_percentage_overall:null}},'UZB',2026,50);assert.equal(p.metrics.goals,0);assert.equal(p.metrics.assists,null);assert.equal(p.metrics.xG,null);assert.equal(p.metrics.shotsPer90,1.25);assert.equal(l.number(false),null);assert.equal(l.number(' '),null);});
test('provider identities require exact name and DOB or a reviewed crosswalk; ambiguous matches stay unlinked',async()=>{const l=await lib(),p=l.normalizePlayer({id:7,full_name:'Test Player',birthday:1000000000},'UZB',2026,50),primary=[{sofaId:9,league:'UZB',name:'Test Player',dateOfBirthTimestamp:1000000000}];assert.equal(l.reconcile([p],primary,{})[0].sofaId,9);assert.equal(l.reconcile([p],[{...primary[0],dateOfBirthTimestamp:null}],{})[0].sofaId,null);assert.equal(l.reconcile([p],[...primary,{...primary[0],sofaId:10}],{})[0].sofaId,null);assert.equal(l.reconcile([p],[{...primary[0],name:'Different',dateOfBirthTimestamp:null}],{playerLinks:{'UZB:7':9}})[0].sofaId,9);});
test('season discovery never borrows another year, country or ambiguous competition',async()=>{const {resolveSeason}=await lib();const e={country:'Uzbekistan',names:['Super League']};const leagues=[{country:'Uzbekistan',league_name:'Super League',season:[{id:40,year:2025},{id:50,year:2026}]}];assert.equal(resolveSeason(leagues,e,2026),50);assert.equal(resolveSeason(leagues,e,2027),null);assert.equal(resolveSeason([...leagues,{...leagues[0],season:[{id:51,year:2026}]}],e,2026),null);});
test('league players paginate beyond the first 200 and retain include=stats',async()=>{const {fetchPlayers}=await lib();const urls=[];const fetcher=async url=>{urls.push(url);const page=Number(url.searchParams.get('page'));return {ok:true,json:async()=>({success:true,data:page===1?Array.from({length:200},(_,i)=>({id:i+1})):[{id:201}],pager:{max_page:2}})};};assert.equal((await fetchPlayers(50,'secret',fetcher)).length,201);assert.equal(urls.length,2);assert.equal(urls[0].searchParams.get('include'),'stats');assert.equal(urls[1].searchParams.get('page'),'2');});
test('failed requests expose no keyed URL',async()=>{const {apiRequest}=await lib();await assert.rejects(apiRequest('/league-list',{},'secret',async()=>({ok:false,status:403})),e=>e.message==='FootyStats HTTP 403'&&!e.message.includes('secret'));});
test('missing credentials record not_configured without destroying snapshots',async()=>{const {sync}=await import('../scripts/sync_footystats.mjs');const root=fs.mkdtempSync(path.join(os.tmpdir(),'uzstat-footy-'));try{fs.mkdirSync(path.join(root,'data/footystats'),{recursive:true});fs.writeFileSync(path.join(root,'data/footystats/UZB-2026.json'),'keep');let called=false;const s=await sync({root,key:'',fetcher:()=>{called=true;}});assert.equal(s.state,'not_configured');assert.equal(called,false);assert.equal(fs.readFileSync(path.join(root,'data/footystats/UZB-2026.json'),'utf8'),'keep');}finally{fs.rmSync(root,{recursive:true,force:true});}});
test('successful synchronization writes linked real-season snapshots; keys stay out of saved data',async()=>{const {sync}=await import('../scripts/sync_footystats.mjs');const root=fs.mkdtempSync(path.join(os.tmpdir(),'uzstat-footy-'));try{fs.mkdirSync(path.join(root,'data/footystats'),{recursive:true});fs.writeFileSync(path.join(root,'data/footystats/config.json'),JSON.stringify({leagues:{UZB:{country:'Uzbekistan',names:['Super League']}},playerLinks:{}}));fs.writeFileSync(path.join(root,'data/superliga_stats.json'),JSON.stringify([{league:'UZB',sofaId:9,name:'Test Player',dateOfBirthTimestamp:1000000000}]));const fetcher=async url=>({ok:true,json:async()=>({success:true,data:url.pathname==='/league-list'?[{country:'Uzbekistan',league_name:'Super League',season:[{id:50,year:2026}]}]:[{id:7,competition_id:50,full_name:'Test Player',birthday:1000000000,goals_overall:0}]})});const s=await sync({root,key:'private-key',fetcher});assert.equal(s.state,'connected');assert.equal(s.leagues.UZB.linked,1);const data=fs.readFileSync(path.join(root,'data/footystats/UZB-2026.json'),'utf8');assert.ok(!data.includes('private-key'));assert.equal(JSON.parse(data).players[0].metrics.goals,0);}finally{fs.rmSync(root,{recursive:true,force:true});}});
