'use client';
import React,{useState} from 'react';
import type {Language,Player,Position,DetailedPosition,SeasonMode} from '@/types/players';
import type {MatchCore} from '@/types/matches';
import type {TeamNeed,ReviewMetric,ReviewTarget,TrackedDecision} from '@/types/decisions';
import {useDecisionStore} from '@/hooks/use-decision-store';
import {evaluateDecision,metricSnapshot,parseDecisionStore,targetMatches} from '@/lib/decisions';
const tr=(l:Language,r:string,u:string)=>l==='ru'?r:u;
const fmt=(v:number|null)=>v===null?'—':v.toFixed(2);
export const reviewLabels:Record<ReviewMetric,[string,string]>={teamPoints:['Очки / матч','Ochko / o‘yin'],teamGoals:['Забито / матч','Urilgan gol / o‘yin'],teamConceded:['Пропущено / матч','O‘tkazilgan gol / o‘yin'],goals:['Голы / 90','Gollar / 90'],assists:['Ассисты / 90','Assistlar / 90'],shots:['Удары / 90','Zarbalar / 90'],keyPasses:['Передачи под удар / 90','Zarbaga pas / 90'],tackles:['Отборы / 90','To‘p qaytarish / 90'],interceptions:['Перехваты / 90','To‘pni to‘xtatish / 90'],saves:['Сейвы / 90','Seyvlar / 90'],xG:['xG / 90','xG / 90'],xA:['xA / 90','xA / 90']};
const storageError=(lang:Language)=>tr(lang,'Не удалось прочитать или сохранить записи. Существующие данные не перезаписаны.','Yozuvlarni o‘qish yoki saqlash imkoni yo‘q. Mavjud ma’lumot o‘zgarmadi.');
export interface NeedSeed {position:Position;detailedPosition:DetailedPosition|null;evidence:string}
export function NeedForm({core,teamId,seasonId,seed,lang,onDone}:{core:MatchCore;teamId:number;seasonId:number;seed:NeedSeed;lang:Language;onDone:(need:TeamNeed)=>void}){
  const {ready,error,update}=useDecisionStore();const [observation,setObservation]=useState(''),[requirement,setRequirement]=useState('');
  const teamName=core.teams.find(t=>t.id===teamId)?.name||String(teamId),season=Object.values(core.seasons).flat().find(s=>s.id===seasonId)!;
  const matches=core.matches.filter(m=>m.seasonId===seasonId&&(m.homeTeamId===teamId||m.awayTeamId===teamId));
  return <form className="analysis-card decision-form" onSubmit={e=>{e.preventDefault();if(!matches.length||!observation.trim()||!requirement.trim())return;const need:TeamNeed={id:crypto.randomUUID(),league:matches[0].league,teamId,teamName,seasonId,seasonName:season.name,position:seed.position,detailedPosition:seed.detailedPosition,observation:observation.trim(),requirement:requirement.trim(),evidence:seed.evidence,matchIds:matches.map(m=>m.id),createdAt:new Date().toISOString(),status:'open',candidates:[]};if(update(s=>({...s,needs:[...s.needs,need]})))onDone(need);}}>
    <h3>{tr(lang,'Потребность команды','Jamoa ehtiyoji')} · {seed.detailedPosition||seed.position}</h3><p className="muted">{seed.evidence}</p>
    <label>{tr(lang,'Что требуется изменить в игре команды?','Jamoa o‘yinida nimani o‘zgartirish kerak?')}<textarea required maxLength={2000} value={observation} onChange={e=>setObservation(e.target.value)}/></label>
    <label>{tr(lang,'Что должен дать новый игрок?','Yangi futbolchi nima berishi kerak?')}<textarea required maxLength={2000} value={requirement} onChange={e=>setRequirement(e.target.value)}/></label>
    {error&&<p role="alert">{storageError(lang)}</p>}<button className="action-primary" disabled={!ready}>{tr(lang,'Сохранить потребность и искать','Ehtiyojni saqlash va qidirish')} →</button>
  </form>;
}
export function CandidateLinkButton({needId,player,lang,fitScore,fitReasons=[]}:{needId:string;player:Player;lang:Language;fitScore?:number;fitReasons?:string[]}){
  const {store,ready,error,update}=useDecisionStore();const need=store.needs.find(n=>n.id===needId);
  if(!need)return null;const linked=need.candidates.some(c=>c.playerId===Number(player.id.split('-')[1]));
  const compatible=need.status==='open'&&need.league===player.league&&player.statsSeasonIds?.length===1&&player.statsSeasonIds[0]===need.seasonId&&player.position===need.position&&(!need.detailedPosition||need.detailedPosition===player.detailedPosition);
  return <div className="candidate-link"><button className="action-secondary" disabled={!ready||linked||!compatible} onClick={()=>update(s=>({...s,needs:s.needs.map(n=>n.id===needId?{...n,candidates:[...n.candidates.filter(c=>c.playerId!==Number(player.id.split('-')[1])),{playerId:Number(player.id.split('-')[1]),name:player.name[lang],position:player.position,addedAt:new Date().toISOString(),reason:need.requirement,metrics:player.roleMetrics||{},seasonIds:player.statsSeasonIds||[],matchIds:[...new Set(Object.values(player.statsMetricDetails||{}).flatMap(d=>d.eventIds||[]))],fitScore,fitReasons}]}:n)}))}>{linked?tr(lang,'В потребности команды ✓','Jamoa ehtiyojida ✓'):tr(lang,'Добавить к потребности','Ehtiyojga qo‘shish')}</button>{!compatible&&!linked&&<small>{tr(lang,'Нужны позиция и сезон этой потребности.','Shu ehtiyoj pozitsiyasi va mavsumi kerak.')}</small>}{error&&<p role="alert">{storageError(lang)}</p>}</div>;
}
function DecisionForm({core,clubTeamId,seasonId,lang,need,initialPlayerId,onSaved}:{core:MatchCore;clubTeamId:number;seasonId:number;lang:Language;need?:TeamNeed;initialPlayerId?:number;onSaved:()=>void}){
  const {ready,error,update}=useDecisionStore();const [subject,setSubject]=useState(initialPlayerId?String(initialPlayerId):'team'),[metric,setMetric]=useState<ReviewMetric>(initialPlayerId?'keyPasses':'teamPoints');
  const [observation,setObservation]=useState(need?.observation||''),[action,setAction]=useState(''),[threshold,setThreshold]=useState(''),[direction,setDirection]=useState<'atLeast'|'atMost'>('atLeast'),[count,setCount]=useState(5),[anchor,setAnchor]=useState('live');
  const league=core.matches.find(m=>m.seasonId===seasonId)!.league;
  const target:ReviewTarget={league,seasonId,...(subject==='team'?{teamId:clubTeamId}:{playerId:Number(subject)})};
  const history=targetMatches(core,target);const cutoff=anchor==='live'?Date.now()/1000:Number(anchor);
  const baseline=metricSnapshot(core,target,metric,history.filter(m=>m.date<=cutoff).slice(-count).map(m=>m.id));
  const teamMatchIds=new Set(core.matches.filter(m=>m.seasonId===seasonId&&(m.homeTeamId===clubTeamId||m.awayTeamId===clubTeamId)).map(m=>m.id));
  const ids=new Set(core.appearances.filter(a=>teamMatchIds.has(a.matchId)&&a.teamId===clubTeamId).map(a=>a.playerId));need?.candidates.forEach(c=>ids.add(c.playerId));if(initialPlayerId)ids.add(initialPlayerId);
  const names=new Map(core.players.map(p=>[p.id,p.name]));const subjectName=subject==='team'?core.teams.find(t=>t.id===clubTeamId)?.name||String(clubTeamId):names.get(Number(subject))||String(subject);
  return <form className="analysis-card decision-form" onSubmit={e=>{e.preventDefault();const goal=Number(threshold);if(!action.trim()||!observation.trim()||!threshold.trim()||!Number.isFinite(goal)||goal<0||!baseline.total)return;
    const d:TrackedDecision={id:crypto.randomUUID(),needId:need?.id||null,clubTeamId,target,subjectName,observation:observation.trim(),action:action.trim(),metric,direction,threshold:goal,window:count,minCoverage:0.8,cutoff,retrospective:anchor!=='live',baseline,createdAt:new Date().toISOString(),version:'decision-v1'};
    if(update(s=>({...s,decisions:[...s.decisions,d]})))onSaved();}}>
    <h3>{tr(lang,'Решение и критерий проверки','Qaror va tekshirish mezoni')}</h3>
    <div className="decision-grid"><label>{tr(lang,'Кого отслеживать','Kimni kuzatish')}<select value={subject} onChange={e=>{setSubject(e.target.value);setMetric(e.target.value==='team'?'teamPoints':'keyPasses');setAnchor('live');}}><option value="team">{tr(lang,'Результаты команды','Jamoa natijalari')}</option>{[...ids].map(id=><option key={id} value={id}>{names.get(id)||id}</option>)}</select></label>
    <label>{tr(lang,'Показатель','Ko‘rsatkich')}<select value={metric} onChange={e=>setMetric(e.target.value as ReviewMetric)}>{(Object.keys(reviewLabels) as ReviewMetric[]).filter(k=>k.startsWith('team')===(subject==='team')).map(k=><option key={k} value={k}>{reviewLabels[k][lang==='ru'?0:1]}</option>)}</select></label></div>
    <label>{tr(lang,'Наблюдение','Kuzatuv')}<textarea required maxLength={2000} value={observation} onChange={e=>setObservation(e.target.value)}/></label>
    <label>{tr(lang,'Решение: что делаем и почему','Qaror: nima va nima uchun')}<textarea required maxLength={2000} value={action} onChange={e=>setAction(e.target.value)}/></label>
    <div className="decision-grid"><label>{tr(lang,'Критерий','Mezon')}<select value={direction} onChange={e=>setDirection(e.target.value as typeof direction)}><option value="atLeast">{tr(lang,'Не меньше','Kamida')}</option><option value="atMost">{tr(lang,'Не больше','Ko‘pi bilan')}</option></select><input aria-label={tr(lang,'Целевое значение','Maqsad qiymati')} required type="number" min="0" step="any" value={threshold} onChange={e=>setThreshold(e.target.value)}/></label>
    <label>{tr(lang,'Проверить после','Shundan keyin tekshirish')}<select value={count} onChange={e=>setCount(Number(e.target.value))}>{[3,5,10].map(n=><option key={n} value={n}>{n} {subject==='team'?tr(lang,'матчей','o‘yin'):tr(lang,'участий игрока','futbolchi ishtiroki')}</option>)}</select></label>
    <label>{tr(lang,'Начало наблюдения','Kuzatish boshlanishi')}<select value={anchor} onChange={e=>setAnchor(e.target.value)}><option value="live">{tr(lang,'Сейчас — будущие матчи','Hozirdan — kelajak o‘yinlar')}</option>{history.map(m=><option key={m.id} value={m.date}>{tr(lang,'Разбор прошлого после','O‘tmishni tahlil qilish:')} {new Date(m.date*1000).toLocaleDateString(lang==='ru'?'ru-RU':'uz-UZ',{timeZone:'Asia/Tashkent'})} · #{m.id}</option>)}</select></label></div>
    <p className="muted">{tr(lang,'Исходный уровень','Boshlang‘ich daraja')}: {fmt(baseline.value)} · {baseline.covered}/{baseline.total} {tr(lang,'с показателем','ko‘rsatkichli')}. {tr(lang,'Для проверки нужно ≥80% игр / участий с показателем. Сохраняется снимок исходного периода.','Tekshirish uchun o‘yin / ishtiroklarning ≥80% ida ko‘rsatkich kerak. Boshlang‘ich davr nusxasi saqlanadi.')}</p>
    {subject!=='team'&&<p className="muted">{tr(lang,'Отслеживаются доступные участия игрока в этой лиге и сезоне, включая другие клубы. Это не подтверждает трансфер.','Shu liga va mavsumdagi mavjud ishtiroklar, boshqa klublarda ham kuzatiladi. Bu transfer tasdig‘i emas.')}</p>}
    {anchor!=='live'&&<p className="compact-warning">{tr(lang,'Ретроспективный разбор: последующие результаты уже могут быть известны.','O‘tmish tahlili: keyingi natijalar allaqachon ma’lum bo‘lishi mumkin.')}</p>}
    {error&&<p role="alert">{storageError(lang)}</p>}<button className="action-primary" disabled={!ready||!baseline.total}>{tr(lang,'Зафиксировать решение','Qarorni qayd etish')}</button>
  </form>;
}
function DecisionCard({decision:d,core,lang}:{decision:TrackedDecision;core:MatchCore;lang:Language}){
  const {update,error}=useDecisionStore();const [comment,setComment]=useState(d.review?.comment||'');const evaluation=evaluateDecision(core,d),s=evaluation.snapshot;
  const resultLabel={met:tr(lang,'Критерий достигнут','Mezon bajarildi'),missed:tr(lang,'Критерий не достигнут','Mezon bajarilmadi'),insufficient:tr(lang,'Недостаточно новых данных','Yangi ma’lumot yetarli emas')};
  return <article className="analysis-card decision-card"><div className="section-heading"><h3>{d.subjectName}</h3><span className="context-chip">{resultLabel[evaluation.result]}</span></div><p>{d.action}</p><p className="muted">{reviewLabels[d.metric][lang==='ru'?0:1]} {d.direction==='atLeast'?'≥':'≤'} {d.threshold} · {d.window} {tr(lang,'игр / участий','o‘yin / ishtirok')}{d.retrospective?' · '+tr(lang,'ретроспектива','o‘tmish tahlili'):''}</p>
    <div className="decision-comparison"><div><small>{tr(lang,'До решения','Qarordan oldin')}</small><strong>{fmt(d.baseline.value)}</strong><small>{d.baseline.covered}/{d.baseline.total}{d.target.playerId!==undefined&&<> · {d.baseline.minutes} {tr(lang,'мин','daq')}</>}</small></div><div><small>{tr(lang,'После решения','Qarordan keyin')}</small><strong>{fmt(s.value)}</strong><small>{s.covered}/{s.total}{d.target.playerId!==undefined&&<> · {s.minutes} {tr(lang,'мин','daq')}</>}</small></div><div><small>Δ</small><strong>{fmt(evaluation.delta)}</strong><small>{tr(lang,'Осталось игр','Qolgan o‘yinlar')}: {evaluation.remaining}</small></div></div>
    <p className="muted">{tr(lang,'Сравнение доступных данных, не доказательство причинного эффекта решения.','Mavjud ma’lumot taqqoslovi; qaror ta’sirining sababi isbotlanmaydi.')}</p>
    <details><summary>{tr(lang,'Основание и матчи','Asos va o‘yinlar')}</summary><p>{d.observation}</p><p>{tr(lang,'До','Oldin')}: {d.baseline.matchIds.join(', ')||'—'}</p><p>{tr(lang,'После','Keyin')}: {s.matchIds.join(', ')||'—'}</p><p>{tr(lang,'Начало','Boshlanish')}: {new Date(d.cutoff*1000).toLocaleString(lang==='ru'?'ru-RU':'uz-UZ',{timeZone:'Asia/Tashkent'})}</p></details>
    <details><summary>{d.review?tr(lang,'Сохранённая проверка','Saqlangan tekshiruv'):tr(lang,'Сохранить результат проверки','Tekshiruv natijasini saqlash')}</summary>{d.review&&<p>{new Date(d.review.at).toLocaleDateString()} · {resultLabel[d.review.result]} · {fmt(d.review.snapshot.value)}</p>}<label>{tr(lang,'Комментарий аналитика','Tahlilchi izohi')}<textarea maxLength={2000} value={comment} onChange={e=>setComment(e.target.value)}/></label><button className="action-secondary" onClick={()=>update(store=>({...store,decisions:store.decisions.map(x=>x.id===d.id?{...x,review:{at:new Date().toISOString(),result:evaluation.result,snapshot:s,comment}}:x)}))}>{tr(lang,'Сохранить проверку','Tekshiruvni saqlash')}</button></details>{error&&<p role="alert">{storageError(lang)}</p>}
  </article>;
}
export function DecisionWorkspace({core,teamId,seasonId,lang,onRecruit,playerId}:{core:MatchCore;teamId:number;seasonId:number;lang:Language;onRecruit?:(need:TeamNeed)=>void;playerId?:number}){
  const {store,ready,error,update}=useDecisionStore();const [draft,setDraft]=useState<{need?:TeamNeed;playerId?:number}|null>(null),[importError,setImportError]=useState(false);
  const league=core.matches.find(m=>m.seasonId===seasonId)?.league;
  const needs=store.needs.filter(n=>n.teamId===teamId&&n.seasonId===seasonId&&n.league===league);
  const decisions=store.decisions.filter(d=>d.target.seasonId===seasonId&&d.target.league===league&&(playerId?d.target.playerId===playerId:d.clubTeamId===teamId));
  const due=decisions.filter(d=>!d.review&&evaluateDecision(core,d).remaining===0).length;
  return <section className="decision-workspace"><div className="section-heading"><h3>{tr(lang,'Наблюдение → решение → проверка','Kuzatuv → qaror → tekshiruv')}</h3><button className="action-primary" disabled={!ready} onClick={()=>setDraft({playerId})}>{tr(lang,'Новое решение','Yangi qaror')}</button></div>
    <p className="muted">{tr(lang,'Записи сохраняются в этом браузере. После обновления матчей сравнение пересчитывается при открытии.','Yozuvlar shu brauzerda saqlanadi. O‘yinlar yangilangach, ochilganda taqqoslash qayta hisoblanadi.')}</p>{due>0&&<p role="status" className="compact-warning">{tr(lang,'Пора проверить решений','Tekshirish vaqti kelgan qarorlar')}: {due}</p>}{error&&<p role="alert">{storageError(lang)}</p>}
    {draft&&<><DecisionForm key={`${draft.need?.id||'new'}:${draft.playerId||'team'}`} core={core} clubTeamId={teamId} seasonId={seasonId} lang={lang} need={draft.need} initialPlayerId={draft.playerId} onSaved={()=>setDraft(null)}/><button className="text-link" onClick={()=>setDraft(null)}>{tr(lang,'Отмена','Bekor qilish')}</button></>}
    {!playerId&&needs.map(n=><article className="analysis-card need-card" key={n.id}><div className="section-heading"><h3>{n.detailedPosition||n.position} · {n.observation}</h3><button className="text-link" onClick={()=>update(s=>({...s,needs:s.needs.map(x=>x.id===n.id?{...x,status:x.status==='open'?'closed':'open'}:x)}))}>{n.status==='open'?tr(lang,'Закрыть потребность','Ehtiyojni yopish'):tr(lang,'Открыть снова','Qayta ochish')}</button></div><p>{n.requirement}</p><details><summary>{tr(lang,'Основание','Asos')}</summary><p>{n.evidence}</p><p>{n.matchIds.join(', ')}</p></details>{onRecruit&&n.status==='open'&&<button className="action-secondary" onClick={()=>onRecruit(n)}>{tr(lang,'Продолжить подбор','Qidirishni davom ettirish')} →</button>}
    {n.candidates.slice().sort((a,b)=>(b.fitScore??-1)-(a.fitScore??-1)).map(c=><div className="need-candidate" key={c.playerId}><div><strong>{c.name}</strong>{typeof c.fitScore==='number'&&<span className="context-chip">Fit {c.fitScore}/100</span>}</div><span>{c.reason}</span><div className="need-candidate-actions"><button className="action-secondary" onClick={()=>setDraft({need:n,playerId:c.playerId})}>{tr(lang,'Принять решение по кандидату','Nomzod bo‘yicha qaror')}</button><button className="text-link" onClick={()=>update(s=>({...s,needs:s.needs.map(x=>x.id===n.id?{...x,candidates:x.candidates.filter(candidate=>candidate.playerId!==c.playerId)}:x)}))}>{tr(lang,'Убрать','Olib tashlash')}</button></div><details><summary>{tr(lang,'Почему подходит','Nega mos keladi')}</summary>{c.fitReasons?.length?<p>{c.fitReasons.join(' · ')}</p>:null}<p>{Object.entries(c.metrics).map(([k,v])=>`${k}: ${fmt(v)}`).join(' · ')}</p></details></div>)}{!n.candidates.length&&<p className="muted">{tr(lang,'Кандидаты ещё не добавлены.','Nomzodlar hali qo‘shilmagan.')}</p>}</article>)}
    {decisions.slice().reverse().map(d=><DecisionCard key={d.id} decision={d} core={core} lang={lang}/>)}
    {!decisions.length&&!draft&&<p className="empty-inline">{tr(lang,'Зафиксируйте действие, измеримый критерий и срок — система сравнит следующие игры с исходным периодом.','Harakat, o‘lchanadigan mezon va muddatni qayd eting — tizim keyingi o‘yinlarni boshlang‘ich davr bilan taqqoslaydi.')}</p>}
    <details className="explanation"><summary>{tr(lang,'Резервная копия решений и потребностей','Qarorlar va ehtiyojlar zaxirasi')}</summary><button className="action-secondary" disabled={!ready} onClick={()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(store,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='uzstat-decisions.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}}>{tr(lang,'Экспорт JSON','JSON eksport')}</button><label className="action-secondary">{tr(lang,'Восстановить JSON','JSON tiklash')}<input type="file" accept="application/json" disabled={!ready} onChange={async e=>{const input=e.currentTarget,file=input.files?.[0];if(!file)return;try{if(file.size>2000000)throw Error('large');const incoming=parseDecisionStore(await file.text());if(!update(s=>({...s,needs:[...s.needs,...incoming.needs.filter(n=>!s.needs.some(x=>x.id===n.id))],decisions:[...s.decisions,...incoming.decisions.filter(d=>!s.decisions.some(x=>x.id===d.id))]})))throw Error('save');setImportError(false);}catch{setImportError(true);}input.value='';}}/></label>{importError&&<p role="alert">{tr(lang,'Не удалось восстановить файл. Текущие записи сохранены.','Fayl tiklanmadi. Hozirgi yozuvlar saqlandi.')}</p>}</details>
  </section>;
}
