'use client';
import React,{useState} from 'react';
import type {Language,Player,Position,DetailedPosition,SeasonMode} from '@/types/players';
import type {MatchCore} from '@/types/matches';
import type {TeamNeed,ReviewMetric,ReviewTarget,TrackedDecision,CandidateBoardStatus,CandidateLink} from '@/types/decisions';
import {useDecisionStore} from '@/hooks/use-decision-store';
import {evaluateDecision,metricSnapshot,parseDecisionStore,targetMatches} from '@/lib/decisions';
const tr=(l:Language,r:string,u:string)=>l==='ru'?r:u;
const fmt=(v:number|null)=>v===null?'—':v.toFixed(2);
export const reviewLabels:Record<ReviewMetric,[string,string]>={teamPoints:['Очки / матч','Ochko / o‘yin'],teamGoals:['Забито / матч','Urilgan gol / o‘yin'],teamConceded:['Пропущено / матч','O‘tkazilgan gol / o‘yin'],goals:['Голы / 90','Gollar / 90'],assists:['Ассисты / 90','Assistlar / 90'],shots:['Удары / 90','Zarbalar / 90'],keyPasses:['Передачи под удар / 90','Zarbaga pas / 90'],tackles:['Отборы / 90','To‘p qaytarish / 90'],interceptions:['Перехваты / 90','To‘pni to‘xtatish / 90'],saves:['Сейвы / 90','Seyvlar / 90'],xG:['xG / 90','xG / 90'],xA:['xA / 90','xA / 90']};
const storageError=(lang:Language)=>tr(lang,'Не удалось прочитать или сохранить записи. Существующие данные не перезаписаны.','Yozuvlarni o‘qish yoki saqlash imkoni yo‘q. Mavjud ma’lumot o‘zgarmadi.');
const candidateStatusLabels:Record<CandidateBoardStatus,[string,string]>={
  watching:['Наблюдать','Kuzatish'],
  shortlist:['Shortlist','Shortlist'],
  priority:['Приоритет','Ustuvor'],
  rejected:['Отказ','Rad etildi'],
};
const candidateStatusRank:Record<CandidateBoardStatus,number>={priority:0,shortlist:1,watching:2,rejected:3};
const candidateStatus=(candidate:CandidateLink):CandidateBoardStatus=>candidate.boardStatus||'watching';
const metricLabel=(key:string)=>key.replace(/Per90$/,' / 90').replace(/Pct$/,' %').replace(/([a-z])([A-Z])/g,'$1 $2');
export interface NeedSeed {position:Position;detailedPosition:DetailedPosition|null;evidence:string}
export function NeedForm({core,teamId,seasonId,seed,lang,onDone}:{core:MatchCore;teamId:number;seasonId:number;seed:NeedSeed;lang:Language;onDone:(need:TeamNeed)=>void}){
  const {ready,error,update}=useDecisionStore();const [observation,setObservation]=useState(''),[requirement,setRequirement]=useState('');
  const teamName=core.teams.find(t=>t.id===teamId)?.name||String(teamId),season=Object.values(core.seasons).flat().find(s=>s.id===seasonId)!;
  const matches=core.matches.filter(m=>m.seasonId===seasonId&&(m.homeTeamId===teamId||m.awayTeamId===teamId));
  return <form className="analysis-card decision-form" onSubmit={e=>{e.preventDefault();if(!matches.length||!observation.trim()||!requirement.trim())return;const need:TeamNeed={id:crypto.randomUUID(),league:matches[0].league,teamId,teamName,seasonId,seasonName:season.name,position:seed.position,detailedPosition:seed.detailedPosition,observation:observation.trim(),requirement:requirement.trim(),evidence:seed.evidence,matchIds:matches.map(m=>m.id),createdAt:new Date().toISOString(),status:'open',candidates:[]};if(update(s=>({...s,needs:[...s.needs,need]})))onDone(need);}}>
    <h3>{tr(lang,'Потребность команды','Jamoa ehtiyoji')} · {seed.detailedPosition||seed.position}</h3><p className="muted">{seed.evidence}</p>
    <label>{tr(lang,'Что требуется изменить в игре команды?','Jamoa o‘yinida nimani o‘zgartirish kerak?')}<textarea required maxLength={2000} value={observation} onChange={e=>setObservation(e.target.value)}/></label>
    <label>{tr(lang,'Что должен дать новый игрок?','Yangi futbolchi nima berishi kerak?')}<textarea required maxLength={2000} value={requirement} onChange={e=>setRequirement(e.target.value)}/></label>
    {error&&<p role="alert">{storageError(lang)}</p>}<button className="action-primary" disabled={!ready}>{tr(lang,'Сохранить потребность и искать','Ehtiyojni saqlash va qidirish')} →</button>
  </form>;
}
export function CandidateLinkButton({needId,player,lang,fitScore,fitReasons=[],fitVersion}:{needId:string;player:Player;lang:Language;fitScore?:number;fitReasons?:string[];fitVersion?:string}){
  const {store,ready,error,update}=useDecisionStore();const need=store.needs.find(n=>n.id===needId);
  if(!need)return null;const linked=need.candidates.some(c=>c.playerId===Number(player.id.split('-')[1]));
  const compatible=need.status==='open'&&need.league===player.league&&player.statsSeasonIds?.length===1&&player.statsSeasonIds[0]===need.seasonId&&player.position===need.position&&(!need.detailedPosition||need.detailedPosition===player.detailedPosition);
  return <div className="candidate-link"><button className="action-secondary" disabled={!ready||linked||!compatible} onClick={()=>update(s=>({...s,needs:s.needs.map(n=>n.id===needId?{...n,candidates:[...n.candidates.filter(c=>c.playerId!==Number(player.id.split('-')[1])),{playerId:Number(player.id.split('-')[1]),name:player.name[lang],position:player.position,addedAt:new Date().toISOString(),reason:need.requirement,metrics:player.roleMetrics||{},seasonIds:player.statsSeasonIds||[],matchIds:[...new Set(Object.values(player.statsMetricDetails||{}).flatMap(d=>d.eventIds||[]))],fitScore,fitReasons,fitVersion,boardStatus:'watching' as const,scoutNote:''}]}:n)}))}>{linked?tr(lang,'В потребности команды ✓','Jamoa ehtiyojida ✓'):tr(lang,'Добавить к потребности','Ehtiyojga qo‘shish')}</button>{!compatible&&!linked&&<small>{tr(lang,'Нужны позиция и сезон этой потребности.','Shu ehtiyoj pozitsiyasi va mavsumi kerak.')}</small>}{error&&<p role="alert">{storageError(lang)}</p>}</div>;
}
function DecisionForm({core,clubTeamId,seasonId,lang,need,initialPlayerId,onSaved}:{core:MatchCore;clubTeamId:number;seasonId:number;lang:Language;need?:TeamNeed;initialPlayerId?:number;onSaved:()=>void}){
  const {ready,error,update}=useDecisionStore();const [subject,setSubject]=useState(initialPlayerId?String(initialPlayerId):'team'),[metric,setMetric]=useState<ReviewMetric>(initialPlayerId?'keyPasses':'teamPoints');
  const [observation,setObservation]=useState(need?.observation||''),[action,setAction]=useState(''),[threshold,setThreshold]=useState(''),[direction,setDirection]=useState<'atLeast'|'atMost'>('atLeast'),[count,setCount]=useState(5),[anchor,setAnchor]=useState('live');
  const league=core.matches.find(m=>m.seasonId===seasonId)!.league;
  const target:ReviewTarget={league,seasonId,...(subject==='team'?{teamId:clubTeamId}:{playerId:Number(subject)})};
  const history=targetMatches(core,target);const cutoff=anchor==='live'?Date.now()/1000:Number(anchor);
  const baseline=metricSnapshot(core,target,metric,history.filter(m=>m.date<=cutoff).slice(-count).map(m=>m.id));
  const teamMatchIds=new Set(core.matches.filter(m=>m.seasonId===seasonId&&(m.homeTeamId===clubTeamId||m.awayTeamId===clubTeamId)).map(m=>m.id));
  const ids=new Set(core.appearances.filter(a=>teamMatchIds.has(a.matchId)&&a.teamId===clubTeamId).map(a=>a.playerId));need?.candidates.forEach(c=>ids.add(c.playerId));if(initialPlayerId)ids.add(initialPlayerId);
  const names=new Map(core.players.map(p=>[p.id,p.name]));const subjectName=subject==='team'?core.teams.find(t=>t.id===clubTeamId)?.name||String(clubTeamId):names.get(Number(subject))||String(subject);
  return <form className="analysis-card decision-form" onSubmit={e=>{e.preventDefault();const goal=Number(threshold);if(!action.trim()||!observation.trim()||!threshold.trim()||!Number.isFinite(goal)||goal<0||!baseline.total)return;
    const d:TrackedDecision={id:crypto.randomUUID(),needId:need?.id||null,clubTeamId,target,subjectName,observation:observation.trim(),action:action.trim(),metric,direction,threshold:goal,window:count,minCoverage:0.8,cutoff,retrospective:anchor!=='live',baseline,createdAt:new Date().toISOString(),version:'decision-v1'};
    if(update(s=>({...s,decisions:[...s.decisions,d]})))onSaved();}}>
    <h3>{tr(lang,'Решение и критерий проверки','Qaror va tekshirish mezoni')}</h3>
    <div className="decision-grid"><label>{tr(lang,'Кого отслеживать','Kimni kuzatish')}<select value={subject} onChange={e=>{setSubject(e.target.value);setMetric(e.target.value==='team'?'teamPoints':'keyPasses');setAnchor('live');}}><option value="team">{tr(lang,'Результаты команды','Jamoa natijalari')}</option>{[...ids].map(id=><option key={id} value={id}>{names.get(id)||id}</option>)}</select></label>
    <label>{tr(lang,'Показатель','Ko‘rsatkich')}<select value={metric} onChange={e=>setMetric(e.target.value as ReviewMetric)}>{(Object.keys(reviewLabels) as ReviewMetric[]).filter(k=>k.startsWith('team')===(subject==='team')).map(k=><option key={k} value={k}>{reviewLabels[k][lang==='ru'?0:1]}</option>)}</select></label></div>
    <label>{tr(lang,'Наблюдение','Kuzatuv')}<textarea required maxLength={2000} value={observation} onChange={e=>setObservation(e.target.value)}/></label>
    <label>{tr(lang,'Решение: что делаем и почему','Qaror: nima va nima uchun')}<textarea required maxLength={2000} value={action} onChange={e=>setAction(e.target.value)}/></label>
    <div className="decision-grid"><label>{tr(lang,'Критерий','Mezon')}<select value={direction} onChange={e=>setDirection(e.target.value as typeof direction)}><option value="atLeast">{tr(lang,'Не меньше','Kamida')}</option><option value="atMost">{tr(lang,'Не больше','Ko‘pi bilan')}</option></select><input aria-label={tr(lang,'Целевое значение','Maqsad qiymati')} required type="number" min="0" step="any" value={threshold} onChange={e=>setThreshold(e.target.value)}/></label>
    <label>{tr(lang,'Проверить после','Shundan keyin tekshirish')}<select value={count} onChange={e=>setCount(Number(e.target.value))}>{[3,5,10].map(n=><option key={n} value={n}>{n} {subject==='team'?tr(lang,'матчей','o‘yin'):tr(lang,'участий игрока','futbolchi ishtiroki')}</option>)}</select></label>
    <label>{tr(lang,'Начало наблюдения','Kuzatish boshlanishi')}<select value={anchor} onChange={e=>setAnchor(e.target.value)}><option value="live">{tr(lang,'Сейчас — будущие матчи','Hozirdan — kelajak o‘yinlar')}</option>{history.map(m=><option key={m.id} value={m.date}>{tr(lang,'Разбор прошлого после','O‘tmishni tahlil qilish:')} {new Date(m.date*1000).toLocaleDateString(lang==='ru'?'ru-RU':'uz-UZ',{timeZone:'Asia/Tashkent'})} · #{m.id}</option>)}</select></label></div>
    <p className="muted">{tr(lang,'Исходный уровень','Boshlang‘ich daraja')}: {fmt(baseline.value)} · {baseline.covered}/{baseline.total} {tr(lang,'с показателем','ko‘rsatkichli')}. {tr(lang,'Для проверки нужно ≥80% игр / участий с показателем. Сохраняется снимок исходного периода.','Tekshirish uchun o‘yin / ishtiroklarning ≥80% ida ko‘rsatkich kerak. Boshlang‘ich davr nusxasi saqlanadi.')}</p>
    {subject!=='team'&&<p className="muted">{tr(lang,'Отслеживаются доступные участия игрока в этой лиге и сезоне, включая другие клубы. Это не подтверждает трансфер.','Shu liga va mavsumdagi mavjud ishtiroklar, boshqa klublarda ham kuzatiladi. Bu transfer tasdig‘i emas.')}</p>}
    {anchor!=='live'&&<p className="compact-warning">{tr(lang,'Ретроспективный разбор: последующие результаты уже могут быть известны.','O‘tmish tahlili: keyingi natijalar allaqachon ma’lum bo‘lishi mumkin.')}</p>}
    {error&&<p role="alert">{storageError(lang)}</p>}<button className="action-primary" disabled={!ready||!baseline.total}>{tr(lang,'Зафиксировать решение','Qarorni qayd etish')}</button>
  </form>;
}
function NeedCandidateBoard({need,lang,onDecision,onStatus,onNote,onRecommend,onRemove}:{need:TeamNeed;lang:Language;onDecision:(playerId:number)=>void;onStatus:(playerId:number,status:CandidateBoardStatus)=>void;onNote:(playerId:number,note:string)=>void;onRecommend:(playerId:number|null)=>void;onRemove:(playerId:number)=>void}){
  const candidates=need.candidates.slice().sort((a,b)=>candidateStatusRank[candidateStatus(a)]-candidateStatusRank[candidateStatus(b)]||(b.fitScore??-1)-(a.fitScore??-1)||a.name.localeCompare(b.name));
  const comparison=candidates.filter(c=>candidateStatus(c)!=='rejected').slice(0,5);
  const frequency=new Map<string,number>();
  for(const candidate of comparison)for(const [key,value] of Object.entries(candidate.metrics))if(typeof value==='number'&&Number.isFinite(value))frequency.set(key,(frequency.get(key)||0)+1);
  const metricKeys=[...frequency.entries()].sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0])).slice(0,4).map(([key])=>key);
  return <>
    {!!comparison.length&&<div className="need-compare"><div className="section-heading"><h4>{tr(lang,'Сравнение shortlist','Shortlist taqqoslovi')}</h4><small>{tr(lang,'Снимок показателей на момент добавления','Qo‘shilgan paytdagi ko‘rsatkichlar')}</small></div><div className="table-scroll"><table className="analysis-table need-compare-table"><thead><tr><th>{tr(lang,'Показатель','Ko‘rsatkich')}</th>{comparison.map(candidate=><th key={candidate.playerId}>{candidate.name}{need.recommendedPlayerId===candidate.playerId&&<small>★ {tr(lang,'Рекомендация','Tavsiya')}</small>}</th>)}</tr></thead><tbody><tr><td>Fit</td>{comparison.map(candidate=><td key={candidate.playerId}><strong>{candidate.fitScore??'—'}</strong></td>)}</tr>{metricKeys.map(key=><tr key={key}><td>{metricLabel(key)}</td>{comparison.map(candidate=><td key={candidate.playerId}>{fmt(candidate.metrics[key])}</td>)}</tr>)}</tbody></table></div></div>}
    <div className="candidate-board">{candidates.map(candidate=>{const status=candidateStatus(candidate),recommended=need.recommendedPlayerId===candidate.playerId;return <article key={candidate.playerId} className={`need-candidate board-${status}${recommended?' recommended':''}`}><div className="candidate-board-head"><div><strong>{candidate.name}</strong>{typeof candidate.fitScore==='number'&&<span className="context-chip">Fit {candidate.fitScore}/100</span>}{recommended&&<span className="recommended-chip">★ {tr(lang,'Финальная рекомендация','Yakuniy tavsiya')}</span>}</div><label>{tr(lang,'Статус','Holat')}<select value={status} onChange={e=>onStatus(candidate.playerId,e.target.value as CandidateBoardStatus)}>{(Object.keys(candidateStatusLabels) as CandidateBoardStatus[]).map(value=><option key={value} value={value}>{candidateStatusLabels[value][lang==='ru'?0:1]}</option>)}</select></label></div><span>{candidate.reason}</span><label className="candidate-note">{tr(lang,'Заметка скаута','Skaut izohi')}<textarea defaultValue={candidate.scoutNote||''} maxLength={1500} placeholder={tr(lang,'Что проверить в видео / на стадионе…','Video / stadionda nimani tekshirish…')} onBlur={e=>onNote(candidate.playerId,e.currentTarget.value.trim())}/></label><div className="need-candidate-actions"><button className="action-secondary" onClick={()=>onDecision(candidate.playerId)}>{tr(lang,'Зафиксировать решение','Qarorni qayd etish')}</button><button className={recommended?'action-primary':'action-secondary'} disabled={status==='rejected'} onClick={()=>onRecommend(recommended?null:candidate.playerId)}>{recommended?tr(lang,'Рекомендован ✓','Tavsiya qilindi ✓'):tr(lang,'Сделать рекомендацией','Tavsiya sifatida tanlash')}</button><button className="text-link" onClick={()=>onRemove(candidate.playerId)}>{tr(lang,'Убрать','Olib tashlash')}</button></div><details><summary>{tr(lang,'Почему подходит','Nega mos keladi')}</summary>{candidate.fitVersion&&<p className="muted">Fit {candidate.fitVersion}</p>}{candidate.fitReasons?.length?<p>{candidate.fitReasons.join(' · ')}</p>:null}<p>{Object.entries(candidate.metrics).map(([key,value])=>`${metricLabel(key)}: ${fmt(value)}`).join(' · ')}</p></details></article>;})}</div>
  </>;
}

function printNeedReport(need:TeamNeed, decisions:TrackedDecision[], lang:Language){
  const w=window.open('', '_blank', 'width=900,height=1000');
  if(!w)return;
  const esc=(value:unknown)=>String(value??'—').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]!));
  const candidates=need.candidates.slice().sort((a,b)=>candidateStatusRank[candidateStatus(a)]-candidateStatusRank[candidateStatus(b)]||(b.fitScore??-1)-(a.fitScore??-1));
  const candidateRows=candidates.map((candidate,index)=>{const status=candidateStatusLabels[candidateStatus(candidate)][lang==='ru'?0:1];const recommended=need.recommendedPlayerId===candidate.playerId?'★ ':'';return `<tr><td>${index+1}</td><td>${recommended}${esc(candidate.name)}</td><td>${esc(candidate.position)}</td><td>${candidate.fitScore??'—'}</td><td>${esc(status)}</td><td>${esc(candidate.scoutNote||'—')}</td><td>${esc(candidate.fitReasons?.join(' · ')||candidate.reason)}</td></tr>`;}).join('');
  const decisionRows=decisions.map(d=>`<tr><td>${esc(d.subjectName)}</td><td>${esc(d.action)}</td><td>${esc(d.metric)}</td><td>${d.direction==='atLeast'?'≥':'≤'} ${d.threshold}</td><td>${d.window}</td></tr>`).join('');
  const title=lang==='ru'?'Отчёт по потребности команды':'Jamoa ehtiyoji hisoboti';
  w.document.write(`<!doctype html><html lang="${lang}"><head><title>${esc(title)} — ${esc(need.teamName)}</title><style>@page{size:A4 portrait;margin:12mm}body{font-family:Arial,sans-serif;color:#111827;margin:0}h1{font-size:22px;margin:0 0 6px}h2{font-size:15px;margin:20px 0 8px}.meta{color:#4b5563;font-size:12px}.box{border:1px solid #d1d5db;border-radius:8px;padding:12px;margin:12px 0}table{width:100%;border-collapse:collapse;font-size:11px}th,td{border:1px solid #d1d5db;padding:6px;text-align:left;vertical-align:top}th{background:#f3f4f6}.fit{font-weight:700}.footer{margin-top:20px;border-top:1px solid #e5e7eb;padding-top:8px;font-size:10px;color:#6b7280}</style></head><body><h1>${esc(need.teamName)} · ${esc(need.detailedPosition||need.position)}</h1><div class="meta">${esc(need.seasonName)} · ${new Date(need.createdAt).toLocaleDateString(lang==='ru'?'ru-RU':'uz-UZ')}</div><div class="box"><strong>${lang==='ru'?'Наблюдение':'Kuzatuv'}</strong><p>${esc(need.observation)}</p><strong>${lang==='ru'?'Что должен дать игрок':'Futbolchi nima berishi kerak'}</strong><p>${esc(need.requirement)}</p><strong>${lang==='ru'?'Основание':'Asos'}</strong><p>${esc(need.evidence)}</p></div><h2>${lang==='ru'?'Shortlist кандидатов':'Nomzodlar short-listi'} · ${candidates.length}</h2><table><thead><tr><th>#</th><th>${lang==='ru'?'Игрок':'Futbolchi'}</th><th>${lang==='ru'?'Позиция':'Pozitsiya'}</th><th>Fit</th><th>${lang==='ru'?'Статус':'Holat'}</th><th>${lang==='ru'?'Заметка':'Izoh'}</th><th>${lang==='ru'?'Почему подходит':'Nega mos'}</th></tr></thead><tbody>${candidateRows||`<tr><td colspan="7">—</td></tr>`}</tbody></table><h2>${lang==='ru'?'Зафиксированные решения':'Qayd etilgan qarorlar'} · ${decisions.length}</h2><table><thead><tr><th>${lang==='ru'?'Объект':'Obyekt'}</th><th>${lang==='ru'?'Действие':'Harakat'}</th><th>${lang==='ru'?'Метрика':'Metrika'}</th><th>${lang==='ru'?'Критерий':'Mezon'}</th><th>${lang==='ru'?'Горизонт':'Muddat'}</th></tr></thead><tbody>${decisionRows||`<tr><td colspan="5">—</td></tr>`}</tbody></table><div class="footer">UzStat · ${title}</div><script>window.onload=()=>{window.print();setTimeout(()=>window.close(),500)}<\/script></body></html>`);
  w.document.close();
}

function DecisionCard({decision:d,core,lang}:{decision:TrackedDecision;core:MatchCore;lang:Language}){
  const {update,error}=useDecisionStore();const [comment,setComment]=useState(d.review?.comment||'');const evaluation=evaluateDecision(core,d),s=evaluation.snapshot;
  const resultLabel={met:tr(lang,'Критерий достигнут','Mezon bajarildi'),missed:tr(lang,'Критерий не достигнут','Mezon bajarilmadi'),insufficient:tr(lang,'Недостаточно новых данных','Yangi ma’lumot yetarli emas')};
  return <article className="analysis-card decision-card"><div className="section-heading"><h3>{d.subjectName}</h3><span className="context-chip">{resultLabel[evaluation.result]}</span></div><p>{d.action}</p><p className="muted">{reviewLabels[d.metric][lang==='ru'?0:1]} {d.direction==='atLeast'?'≥':'≤'} {d.threshold} · {d.window} {tr(lang,'игр / участий','o‘yin / ishtirok')}{d.retrospective?' · '+tr(lang,'ретроспектива','o‘tmish tahlili'):''}</p>
    <div className="decision-comparison"><div><small>{tr(lang,'До решения','Qarordan oldin')}</small><strong>{fmt(d.baseline.value)}</strong><small>{d.baseline.covered}/{d.baseline.total}{d.target.playerId!==undefined&&<> · {d.baseline.minutes} {tr(lang,'мин','daq')}</>}</small></div><div><small>{tr(lang,'После решения','Qarordan keyin')}</small><strong>{fmt(s.value)}</strong><small>{s.covered}/{s.total}{d.target.playerId!==undefined&&<> · {s.minutes} {tr(lang,'мин','daq')}</>}</small></div><div><small>Δ</small><strong>{fmt(evaluation.delta)}</strong><small>{tr(lang,'Осталось игр','Qolgan o‘yinlar')}: {evaluation.remaining}</small></div></div>
    <p className="muted">{tr(lang,'Сравнение доступных данных, не доказательство причинного эффекта решения.','Mavjud ma’lumot taqqoslovi; qaror ta’sirining sababi isbotlanmaydi.')}</p>
    <details><summary>{tr(lang,'Основание и матчи','Asos va o‘yinlar')}</summary><p>{d.observation}</p><p>{tr(lang,'До','Oldin')}: {d.baseline.matchIds.join(', ')||'—'}</p><p>{tr(lang,'После','Keyin')}: {s.matchIds.join(', ')||'—'}</p><p>{tr(lang,'Начало','Boshlanish')}: {new Date(d.cutoff*1000).toLocaleString(lang==='ru'?'ru-RU':'uz-UZ',{timeZone:'Asia/Tashkent'})}</p></details>
    <details><summary>{d.review?tr(lang,'Сохранённая проверка','Saqlangan tekshiruv'):tr(lang,'Сохранить результат проверки','Tekshiruv natijasini saqlash')}</summary>{d.review&&<p>{new Date(d.review.at).toLocaleDateString()} · {resultLabel[d.review.result]} · {fmt(d.review.snapshot.value)}</p>}<label>{tr(lang,'Комментарий аналитика','Tahlilchi izohi')}<textarea maxLength={2000} value={comment} onChange={e=>setComment(e.target.value)}/></label><button className="action-secondary" onClick={()=>update(store=>({...store,decisions:store.decisions.map(x=>x.id===d.id?{...x,review:{at:new Date().toISOString(),result:evaluation.result,snapshot:s,comment}}:x)}))}>{tr(lang,'Сохранить проверку','Tekshiruvni saqlash')}</button></details>{error&&<p role="alert">{storageError(lang)}</p>}
  </article>;
}
export function DecisionWorkspace({core,teamId,seasonId,lang,onRecruit,playerId}:{core:MatchCore;teamId:number;seasonId:number;lang:Language;onRecruit?:(need:TeamNeed)=>void;playerId?:number}){
  const {store,ready,error,update}=useDecisionStore();const [draft,setDraft]=useState<{need?:TeamNeed;playerId?:number}|null>(null),[importError,setImportError]=useState(false);
  const league=core.matches.find(m=>m.seasonId===seasonId)?.league;
  const needs=store.needs.filter(n=>n.teamId===teamId&&n.seasonId===seasonId&&n.league===league);
  const decisions=store.decisions.filter(d=>d.target.seasonId===seasonId&&d.target.league===league&&(playerId?d.target.playerId===playerId:d.clubTeamId===teamId));
  const due=decisions.filter(d=>!d.review&&evaluateDecision(core,d).remaining===0).length;
  const openNeeds=needs.filter(n=>n.status==='open').length;
  const linkedCandidates=needs.reduce((sum,n)=>sum+n.candidates.length,0);
  return <section className="decision-workspace"><div className="section-heading"><h3>{tr(lang,'Наблюдение → решение → проверка','Kuzatuv → qaror → tekshiruv')}</h3><button className="action-primary" disabled={!ready} onClick={()=>setDraft({playerId})}>{tr(lang,'Новое решение','Yangi qaror')}</button></div>
    <p className="muted">{tr(lang,'Записи сохраняются в этом браузере. После обновления матчей сравнение пересчитывается при открытии.','Yozuvlar shu brauzerda saqlanadi. O‘yinlar yangilangach, ochilganda taqqoslash qayta hisoblanadi.')}</p>
    {!playerId&&<div className="decision-funnel"><div><small>{tr(lang,'Открытые потребности','Ochiq ehtiyojlar')}</small><strong>{openNeeds}</strong></div><div><small>{tr(lang,'Кандидаты в потребностях','Ehtiyojlardagi nomzodlar')}</small><strong>{linkedCandidates}</strong></div><div><small>{tr(lang,'Решения','Qarorlar')}</small><strong>{decisions.length}</strong></div><div><small>{tr(lang,'Пора проверить','Tekshirish vaqti')}</small><strong>{due}</strong></div></div>}
    {due>0&&<p role="status" className="compact-warning">{tr(lang,'Пора проверить решений','Tekshirish vaqti kelgan qarorlar')}: {due}</p>}{error&&<p role="alert">{storageError(lang)}</p>}
    {draft&&<><DecisionForm key={`${draft.need?.id||'new'}:${draft.playerId||'team'}`} core={core} clubTeamId={teamId} seasonId={seasonId} lang={lang} need={draft.need} initialPlayerId={draft.playerId} onSaved={()=>setDraft(null)}/><button className="text-link" onClick={()=>setDraft(null)}>{tr(lang,'Отмена','Bekor qilish')}</button></>}
    {!playerId&&needs.map(n=><article className="analysis-card need-card" key={n.id}><div className="section-heading"><h3>{n.detailedPosition||n.position} · {n.observation}</h3><div className="need-heading-actions"><span className="context-chip">{n.candidates.length} {tr(lang,'кандидатов','nomzod')}</span><button className="text-link" onClick={()=>printNeedReport(n,decisions.filter(d=>d.needId===n.id),lang)}>{tr(lang,'Отчёт / PDF','Hisobot / PDF')}</button><button className="text-link" onClick={()=>update(s=>({...s,needs:s.needs.map(x=>x.id===n.id?{...x,status:x.status==='open'?'closed':'open'}:x)}))}>{n.status==='open'?tr(lang,'Закрыть потребность','Ehtiyojni yopish'):tr(lang,'Открыть снова','Qayta ochish')}</button></div></div><p>{n.requirement}</p><details><summary>{tr(lang,'Основание','Asos')}</summary><p>{n.evidence}</p><p>{n.matchIds.join(', ')}</p></details>{onRecruit&&n.status==='open'&&<button className="action-secondary" onClick={()=>onRecruit(n)}>{tr(lang,'Продолжить подбор','Qidirishni davom ettirish')} →</button>}
    {n.candidates.length?<NeedCandidateBoard need={n} lang={lang} onDecision={playerId=>setDraft({need:n,playerId})} onStatus={(playerId,status)=>update(s=>({...s,needs:s.needs.map(x=>x.id===n.id?{...x,recommendedPlayerId:status==='rejected'&&x.recommendedPlayerId===playerId?null:x.recommendedPlayerId,candidates:x.candidates.map(candidate=>candidate.playerId===playerId?{...candidate,boardStatus:status}:candidate)}:x)}))} onNote={(playerId,note)=>update(s=>({...s,needs:s.needs.map(x=>x.id===n.id?{...x,candidates:x.candidates.map(candidate=>candidate.playerId===playerId?{...candidate,scoutNote:note}:candidate)}:x)}))} onRecommend={playerId=>update(s=>({...s,needs:s.needs.map(x=>x.id===n.id?{...x,recommendedPlayerId:playerId}:x)}))} onRemove={playerId=>update(s=>({...s,needs:s.needs.map(x=>x.id===n.id?{...x,recommendedPlayerId:x.recommendedPlayerId===playerId?null:x.recommendedPlayerId,candidates:x.candidates.filter(candidate=>candidate.playerId!==playerId)}:x)}))}/>:<p className="muted">{tr(lang,'Кандидаты ещё не добавлены.','Nomzodlar hali qo‘shilmagan.')}</p>}</article>)}
    {decisions.slice().reverse().map(d=><DecisionCard key={d.id} decision={d} core={core} lang={lang}/>)}
    {!decisions.length&&!draft&&<p className="empty-inline">{tr(lang,'Зафиксируйте действие, измеримый критерий и срок — система сравнит следующие игры с исходным периодом.','Harakat, o‘lchanadigan mezon va muddatni qayd eting — tizim keyingi o‘yinlarni boshlang‘ich davr bilan taqqoslaydi.')}</p>}
    <details className="explanation"><summary>{tr(lang,'Резервная копия решений и потребностей','Qarorlar va ehtiyojlar zaxirasi')}</summary><button className="action-secondary" disabled={!ready} onClick={()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(store,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='uzstat-decisions.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}}>{tr(lang,'Экспорт JSON','JSON eksport')}</button><label className="action-secondary">{tr(lang,'Восстановить JSON','JSON tiklash')}<input type="file" accept="application/json" disabled={!ready} onChange={async e=>{const input=e.currentTarget,file=input.files?.[0];if(!file)return;try{if(file.size>2000000)throw Error('large');const incoming=parseDecisionStore(await file.text());if(!update(s=>({...s,needs:[...s.needs,...incoming.needs.filter(n=>!s.needs.some(x=>x.id===n.id))],decisions:[...s.decisions,...incoming.decisions.filter(d=>!s.decisions.some(x=>x.id===d.id))]})))throw Error('save');setImportError(false);}catch{setImportError(true);}input.value='';}}/></label>{importError&&<p role="alert">{tr(lang,'Не удалось восстановить файл. Текущие записи сохранены.','Fayl tiklanmadi. Hozirgi yozuvlar saqlandi.')}</p>}</details>
  </section>;
}
